name = "Cobblemon Teal"
author = "ItsMeTrevor"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d13ccc496329eeb76bccdd76229f8e8fa5455c7c4a071dd089208a6acf1fffff"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
