name = "Cobblemon Teal"
author = "ItsMeTrevor"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38e2b2e7c782ebeb7ec55b5dc1e9d3d68f7d69106befd6a8fee71169dbcabf40"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
