name = "Cobblemon Teal"
author = "ItsMeTrevor"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2971d23d3b218baac7bec045cb0fbe3c0b412be36c0bfadff5f572c0bbc8f2b0"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
