name = "Cobblemon Teal"
author = "ItsMeTrevor"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f237bc93813b2be669cdc5ff0a29e857e16d9438f1ce96303c6faac29180ae5e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
